---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  this template does XXXX

Metadata:
  template metadata

Parameters:
  set of parameters

Mappings:
  set of mappings

Conditions:
  set of conditions

Transform:
  set of transforms

Resources:
  set of resources

Outputs:
  set of outputs
